### ISSUE TITLE
`RequestResponsePactOps` needs support for passing a scala Map to `.given()`

### ISSUE THREAD

**Issue by solarmosaic-kflorence** [jbwheatley/pact4s#38]
When specifying a provider state with `.given()`, the second argument can be a Map of parameters. We should add support for using a scala Map there like we have for `.headers`.

**Comment by jbwheatley** [comment]
fixed in `0.0.13`

**Comment by solarmosaic-kflorence** [comment]
@jbwheatley looks like this is still missing on `PactDslWithProvider` (which is the case if it's applied as the very first statement). For example:

```scala
ConsumerPactBuilder
  .consumer(consumerName)
  .hasPactWith(providerName)
  .given("greeting", Map("name" -> "world"))
```

Seems to be working in other cases though (I tested `PactDslResponse` specifically)

**Comment by solarmosaic-kflorence** [comment]
^ the above was fixed in `0.0.15`
